Repository kalviumcommunity/Supply-Chain-Cargo-Management-Maersk-Hackathon, pull requests merged in 2025-10, with the labels that each got.

#11 [FEAT] Vue Dashboard Component
  client/bun.lock
  client/index.html
  client/package.json
  client/src/App.vue
  client/src/components/Dashboard.vue
  client/src/components/HelloWorld.vue
  client/src/style.css
  client/vite.config.js
Labels: enhancement, Review effort 2/5, Review effort 3/5

#16 [FEAT] Initialize Spring Boot backend with PostgreSQL database connection
  server/.gitignore
  server/pom.xml
  server/src/main/java/com/cargomanagement/CargoManagementApplication.java
  server/src/main/resources/application.properties
Labels: Review effort 2/5, Possible security concern

#18 [FEAT] Vue CargoManagement Component
  client/package.json
  client/src/components/CargoManagement.vue
  client/src/router/index.js
Labels: enhancement, Review effort 2/5

#20 [FEAT] Day 6 Backend LLD: JPA Entity Models for All Core Entities (Cargo, Delivery, Route, Shipment, Vendor from Schema/ERD)
  server/.gitignore
  server/src/main/java/com/cargomanagement/models/Cargo.java
  server/src/main/java/com/cargomanagement/models/Delivery.java
  server/src/main/java/com/cargomanagement/models/Route.java
  server/src/main/java/com/cargomanagement/models/Shipment.java
  server/src/main/java/com/cargomanagement/models/Vendor.java
Labels: Review effort 2/5

#22 [FEAT] Vue Route Management Component
  client/src/components/RouteManagement.vue
  client/src/router/index.js
Labels: enhancement, Review effort 4/5

#25 [FEAT] Vue Vendor Management Component
  client/src/components/VendorManagement.vue
  client/src/router/index.js
Labels: enhancement, Review effort 3/5, Review effort 4/5

#26 [FEAT] Implement ORM Repositories for Core Entities in Supply Chain Management
  server/src/main/java/com/cargomanagement/models/Cargo.java
  server/src/main/java/com/cargomanagement/models/Route.java
  server/src/main/java/com/cargomanagement/models/Shipment.java
  server/src/main/java/com/cargomanagement/models/Vendor.java
  server/src/main/java/com/cargomanagement/repository/CargoRepository.java
  server/src/main/java/com/cargomanagement/repository/DeliveryRepository.java
  server/src/main/java/com/cargomanagement/repository/RouteRepository.java
  server/src/main/java/com/cargomanagement/repository/ShipmentRepository.java
  server/src/main/java/com/cargomanagement/repository/VendorRepository.java
Labels: Review effort 2/5

#27 [Feat] Implement reusable BaseModal and ConfirmDialog component
  client/src/components/CargoManagement.vue
  client/src/components/shared/BaseModal.vue
  client/src/components/shared/ConfirmDialog.vue
Labels: Review effort 3/5

#29 [DOCS] Backend development workflow documentation
  docs/backend_workflow.md
Labels: Review effort 1/5

#31 [FEAT] Add Kafka Producer Service with KRaft Local Setup and Event Topics
  server/src/main/java/com/cargomanagement/service/KafkaProducerService.java
  server/src/main/resources/application.properties
Labels: Review effort 2/5

#33 [FEAT] Creating Controllers in server
  bruno/bruno.json
  bruno/cargos/cargos-del.bru
  bruno/cargos/cargos-get.bru
  bruno/cargos/cargos-post.bru
  bruno/cargos/cargos-put.bru
  bruno/cargos/folder.bru
  bruno/deliveries/deliveries-get.bru
  bruno/deliveries/delivery-delete.bru
  bruno/deliveries/delivery-post.bru
  bruno/deliveries/delivery-put.bru
  bruno/deliveries/folder.bru
  bruno/routes/folder.bru
  bruno/routes/routes-delete.bru
  bruno/routes/routes-get.bru
  bruno/routes/routes-post.bru
  bruno/routes/routes-put.bru
  bruno/shipments/folder.bru
  bruno/shipments/shipments-delete.bru
  bruno/shipments/shipments-get.bru
  bruno/shipments/shipments-post.bru
  bruno/shipments/shipments-put.bru
  bruno/vendors/folder.bru
  bruno/vendors/vendors-delete.bru
  bruno/vendors/vendors-get.bru
  bruno/vendors/vendors-put.bru
  bruno/vendors/vendors_post.bru
  docs/API_TESTING_GUIDE.md
  server/src/main/java/com/cargomanagement/controller/CargoController.java
  server/src/main/java/com/cargomanagement/controller/DeliveryController.java
  server/src/main/java/com/cargomanagement/controller/RouteController.java
  server/src/main/java/com/cargomanagement/controller/ShipmentController.java
  server/src/main/java/com/cargomanagement/controller/VendorController.java
  server/src/main/java/com/cargomanagement/exception/GlobalExceptionHandler.java
  server/src/main/java/com/cargomanagement/repository/CargoRepository.java
  server/src/main/java/com/cargomanagement/repository/DeliveryRepository.java
  server/src/main/java/com/cargomanagement/repository/RouteRepository.java
  server/src/main/java/com/cargomanagement/repository/ShipmentRepository.java
  server/src/main/java/com/cargomanagement/repository/VendorRepository.java
Labels: documentation, enhancement, Review effort 3/5

#36 [FEAT] Implement Kafka Consumer & Full CRUD Controllers for Core Entities with event publishing
  server/pom.xml
  server/src/main/java/com/cargomanagement/config/SecurityConfig.java
  server/src/main/java/com/cargomanagement/config/WebSocketConfig.java
  server/src/main/java/com/cargomanagement/controller/CargoController.java
  server/src/main/java/com/cargomanagement/controller/DeliveryController.java
  server/src/main/java/com/cargomanagement/controller/RouteController.java
  server/src/main/java/com/cargomanagement/controller/ShipmentController.java
  server/src/main/java/com/cargomanagement/controller/VendorController.java
  server/src/main/java/com/cargomanagement/dto/CargoCreateRequest.java
  server/src/main/java/com/cargomanagement/service/KafkaConsumerService.java
  server/src/main/java/com/cargomanagement/service/KafkaProducerService.java
  server/src/main/resources/application.properties
Labels: Review effort 3/5, Possible security concern
